version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=challenge-emiteai-tms-user
      - POSTGRES_PASSWORD=challenge-emiteai-tms-password
      - POSTGRES_DB=challenge_emiteai_tms_db

  challenge-emiteai-tms-app:
    build: .
    ports:
        - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/challenge_emiteai_tms_db
      - SPRING_DATASOURCE_USERNAME=challenge-emiteai-tms-user
      - SPRING_DATASOURCE_PASSWORD=challenge-emiteai-tms-password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_EXCHANGE=challenge-emiteai-tms-exchange
      - SPRING_RABBITMQ_ROUTING_KEY=challenge-emiteai-tms-routing-key
      - SPRING_RABBITMQ_QUEUE=challenge-emiteai-tms-queue
      - SPRING_RABBITMQ_EXCHANGE_DLX=challenge-emiteai-tms-exchange-dlx
      - SPRING_RABBITMQ_QUEUE_DLQ=challenge-emiteai-tms-queue-dlq
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000